### ISSUE TITLE
Carthage badge is missing

### ISSUE THREAD

**Issue by TofPlay** [qiuncheng/NoticeBar#3]
On your `README.md` [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage) is missing.

**Comment by status302** [comment]
@TofPlay Added at [6a42043](https://github.com/qiuncheng/NoticeBar/commit/6a42043bccaaf853875349c19e829f9d2b6ee78d#diff-04c6e90faac2675aa89e2176d2eec7d8R8)
