### ISSUE TITLE
found a bug...

### ISSUE THREAD

**Issue by pangpingfei** [qiuncheng/NoticeBar#4]
when noticebar is showing, press home key, and return app, it would not restore status bar style, and can not show notice bar again.

**Comment by pangpingfei** [comment]
```swift
private func show(duration: TimeInterval, willShow: (Void) -> Void, completed: @escaping (_ finished: Bool) -> Void) {

        if let subviews = UIApplication.shared.keyWindow?.subviews {
            for view in subviews {
                if view.isKind(of: NoticeBar.self) {
                    return // if this line changed to "view.removeFromSuperview()" could solve this proplem
                }
            }
        }
        willShow()

...

```

**Comment by status302** [comment]
If you want to show notice bar again, just call show function, when show completed, it will be removed from its super view.

**Comment by pangpingfei** [comment]
@qiuncheng cannot show again that i said is mean has called the show func but nothing shown. Your example , too, you can have a try

**Comment by status302** [comment]
Will be fixed later.

**Comment by status302** [comment]
Please update pod to 0.1.5.
