### ISSUE TITLE
Carthage update

### ISSUE THREAD

**Issue by pangpingfei** [qiuncheng/NoticeBar#5]
之前是0.1.4，用carthage update到0.1.5，很奇怪的，原来用show(duration, nil)的地方，第二个不是可选了，但是源代码里这个方法明明没变化，public func show(duration: TimeInterval, completed: ((_ finished: Bool) -> Void)?)，framework中点进去变成了：public func show(duration: TimeInterval, completed: @escaping (Bool) -> Swift.Void)。不知道怎么回事~

**Comment by status302** [comment]
@pangpingfei 你好。
我刚刚使用Carthage测试过了，没什么问题。
![image](https://cloud.githubusercontent.com/assets/9990834/22627693/84ef47c2-ec02-11e6-9e66-271b5e8b2641.png)
![image](https://cloud.githubusercontent.com/assets/9990834/22627709/a76b10d8-ec02-11e6-80a0-ba8461dc3c4a.png)

**Comment by pangpingfei** [comment]
不知道哪里问题，我在其他项目首次Carthage，然后把framework拷贝覆盖到现有项目，能正常使用了……

**Comment by status302** [comment]
这个应该是Carthage使用的问题吧，在使用update的时候先清除一下之前的Carthage build可能有帮助。不过能正常使用了就是好呀。
